import {
  CLASSIFICATION_THRESHOLDS,
  GROUP_FACTOR_WEIGHTS,
  GROUP_WEIGHTS,
} from '../riskAssessment/weights.js'
import { RISK_MODEL_VERSION } from '../riskAssessment/version.js'

export const CATALOG_VERSION = '2026-06'

export const DATASET_REFERENCES = [
  {
    slug: 'inca-dados-e-numeros',
    name: 'INCA - Dados e Números',
    sourceType: 'epidemiological',
    sourceUrl:
      'https://www.gov.br/inca/pt-br/assuntos/gestor-e-profissional-de-saude/controle-do-cancer-de-mama/dados-e-numeros',
    description: 'Brazilian breast cancer epidemiology and public health context.',
    useCase: 'Population context and educational risk framing for Brazil.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'inca-fontes-de-informacao',
    name: 'INCA - Fontes de Informacao',
    sourceType: 'contextual',
    sourceUrl:
      'https://www.gov.br/inca/pt-br/assuntos/gestor-e-profissional-de-saude/controle-do-cancer-de-mama/fontes-de-informacao',
    description: 'Reference portal for public health breast cancer information.',
    useCase: 'Terminology and contextual framing for user-facing guidance.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'seer-female-breast-cancer-stat-facts',
    name: 'Female Breast Cancer Stat Facts (SEER/NCI)',
    sourceType: 'epidemiological',
    sourceUrl: 'https://seer.cancer.gov/statfacts/html/breast.html?statfacts_page=breast.html',
    description: 'Population-level breast cancer incidence and survival summary.',
    useCase: 'Age and incidence context for the heuristic model.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'who-breast-cancer-fact-sheet',
    name: 'OMS - Breast Cancer Fact Sheet',
    sourceType: 'contextual',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/breast-cancer',
    description: 'World Health Organization breast cancer fact sheet.',
    useCase: 'Global health messaging and prevention context.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'iarc-globocan-breast-fact-sheet',
    name: 'IARC/WHO - GLOBOCAN Breast Fact Sheet',
    sourceType: 'epidemiological',
    sourceUrl: 'https://gco.iarc.who.int/media/globocan/factsheets/cancers/20-breast-fact-sheet.pdf',
    description: 'Global breast cancer burden and epidemiology snapshot.',
    useCase: 'Contextual epidemiology for global comparison and age framing.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-breast-cancer-wisconsin-diagnostic',
    name: 'Breast Cancer Wisconsin (Diagnostic) - UCI',
    sourceType: 'clinical',
    sourceUrl:
      'https://archive.ics.uci.edu/ml/datasets/breast%2Bcancer%2Bwisconsin%2B%28diagnostic%29',
    description: 'Classic clinical benchmark dataset for breast cancer diagnosis.',
    useCase: 'Clinical reference for symptom and diagnosis-oriented comparatives.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-breast-cancer-wisconsin-original',
    name: 'Breast Cancer Wisconsin (Original) - UCI',
    sourceType: 'clinical',
    sourceUrl: 'https://archive.ics.uci.edu/dataset/15/breast%2Bcancer%2Bwisconsin%2Boriginal',
    description: 'Original UCI breast cancer benchmark dataset.',
    useCase: 'Legacy clinical comparison reference.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-breast-cancer-wisconsin-prognostic',
    name: 'Breast Cancer Wisconsin (Prognostic) - UCI',
    sourceType: 'clinical',
    sourceUrl: 'https://archive.ics.uci.edu/dataset/16/breast%2Bcancer',
    description: 'UCI prognostic breast cancer benchmark dataset.',
    useCase: 'Prognostic reference for follow-up and recurrence framing.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-breast-cancer-coimbra',
    name: 'Breast Cancer Coimbra - UCI',
    sourceType: 'clinical',
    sourceUrl: 'https://archive.ics.uci.edu/ml/datasets/Breast%20Cancer%20Coimbra',
    description: 'Breast cancer dataset with metabolic and clinical features.',
    useCase: 'Clinical proxy for BMI, metabolic context and reproductive factors.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-mammographic-mass',
    name: 'Mammographic Mass - UCI',
    sourceType: 'clinical',
    sourceUrl: 'https://archive.ics.uci.edu/ml/datasets/mammographic%2Bmass',
    description: 'Clinical dataset with mammographic mass attributes.',
    useCase: 'Mammography-oriented reference for exam and symptom context.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-breast-tissue',
    name: 'Breast Tissue - UCI',
    sourceType: 'clinical',
    sourceUrl: 'https://archive.ics.uci.edu/ml/datasets/Breast%2BTissue',
    description: 'Breast tissue classification benchmark dataset.',
    useCase: 'Clinical texture and tissue context for symptom comparatives.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'uci-breast-cancer-recurrence-non-recurrence',
    name: 'Breast Cancer (recurrence/non-recurrence) - UCI',
    sourceType: 'clinical',
    sourceUrl: 'https://archive.ics.uci.edu/ml/datasets/breast%20cancer',
    description: 'Recurrence and non-recurrence benchmark dataset.',
    useCase: 'Prognostic comparator for recurrence-oriented discussion.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'sklearn-load-breast-cancer',
    name: 'Scikit-learn load_breast_cancer',
    sourceType: 'clinical',
    sourceUrl:
      'https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html',
    description: 'Well-known clinical benchmark dataset packaged with scikit-learn.',
    useCase: 'Baseline benchmark for educational validation and comparisons.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'breakhis',
    name: 'BreaKHis',
    sourceType: 'imaging',
    sourceUrl:
      'https://web.inf.ufpr.br/vri/databases/breast-cancer-histopathological-database-breakhis/',
    description: 'Histopathological image database for breast cancer.',
    useCase: 'Imaging reference if the project expands toward visual analysis.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'cbis-ddsm',
    name: 'CBIS-DDSM - TCIA',
    sourceType: 'imaging',
    sourceUrl: 'https://www.cancerimagingarchive.net/collection/cbis-ddsm/',
    description: 'Curated mammography image collection.',
    useCase: 'Imaging and mammography benchmark reference.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'tcga-brca-imaging-collection',
    name: 'TCGA-BRCA Imaging Collection - IDC',
    sourceType: 'imaging',
    sourceUrl: 'https://portal.imaging.datacommons.cancer.gov/collections/tcga_brca/',
    description: 'Imaging collection linked to TCGA-BRCA.',
    useCase: 'Radiology reference for future image-based extensions.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'gdc-data-portal',
    name: 'NCI Genomic Data Commons (GDC Data Portal)',
    sourceType: 'genomic',
    sourceUrl: 'https://gdc.cancer.gov/access-data/gdc-data-portal',
    description: 'Cancer genomics data portal.',
    useCase: 'Genomic context and biomarker expansion.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'tcga-brca-project',
    name: 'TCGA-BRCA Project - GDC',
    sourceType: 'genomic',
    sourceUrl: 'https://portal.gdc.cancer.gov/projects/TCGA-BRCA',
    description: 'TCGA breast invasive carcinoma project page.',
    useCase: 'Primary genomic project reference for breast cancer.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'cbioportal-metabric',
    name: 'cBioPortal - METABRIC',
    sourceType: 'genomic',
    sourceUrl: 'https://www.cbioportal.org/study/summary?id=brca_metabric',
    description: 'METABRIC breast cancer cohort in cBioPortal.',
    useCase: 'Genomic and molecular subtype reference.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'cbioportal-tcga-breast-invasive-carcinoma',
    name: 'cBioPortal - TCGA Breast Invasive Carcinoma (PanCancer Atlas)',
    sourceType: 'genomic',
    sourceUrl: 'https://www.cbioportal.org/study/summary?id=brca_tcga_pan_can_atlas_2018',
    description: 'PanCancer Atlas breast invasive carcinoma cohort.',
    useCase: 'Genomic and molecular subtype reference for breast cancer.',
    version: CATALOG_VERSION,
    active: true,
  },
  {
    slug: 'geo-gse96058',
    name: 'GEO - GSE96058',
    sourceType: 'genomic',
    sourceUrl: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96058',
    description: 'Public gene expression dataset for breast cancer.',
    useCase: 'Transcriptomic reference for future biomarker-oriented work.',
    version: CATALOG_VERSION,
    active: true,
  },
]

function createMapping({
  datasetReferenceSlug,
  datasetFieldName,
  mappingType,
  evidenceStrength,
  notes,
}) {
  return {
    datasetReferenceSlug,
    datasetFieldName,
    mappingType,
    evidenceStrength,
    notes,
  }
}

export const FIELD_DATASET_MAPPINGS = {
  fullName: [
    createMapping({
      datasetReferenceSlug: 'inca-fontes-de-informacao',
      datasetFieldName: 'user_identity_context',
      mappingType: 'contextual',
      evidenceStrength: 'contextual',
      notes: 'Non-clinical identifier used as metadata only.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'patient_context',
      mappingType: 'contextual',
      evidenceStrength: 'contextual',
      notes: 'Name is kept for UX and audit traceability, not scoring.',
    }),
  ],
  age: [
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'age_at_diagnosis_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population age framing is central for the heuristic.',
    }),
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'age_distribution_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Brazilian epidemiologic age context.',
    }),
    createMapping({
      datasetReferenceSlug: 'iarc-globocan-breast-fact-sheet',
      datasetFieldName: 'age_incidence_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Global incidence context for age bands.',
    }),
  ],
  state: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'regional_context',
      mappingType: 'contextual',
      evidenceStrength: 'contextual',
      notes: 'Used for regional public health context only.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'geographic_context',
      mappingType: 'contextual',
      evidenceStrength: 'contextual',
      notes: 'Keeps state as a segmentation and audit dimension.',
    }),
  ],
  cancerDiagnosis: [
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-wisconsin-prognostic',
      datasetFieldName: 'prognostic_outcome',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Outcome-oriented benchmark reference for prior diagnosis context.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-recurrence-non-recurrence',
      datasetFieldName: 'recurrence_status',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Recurrence-oriented benchmark for historical diagnosis.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'survival_and_prevalence_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Supports historical diagnosis framing with population data.',
    }),
  ],
  familyBreastCancer: [
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'family_history_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population-level family history context.',
    }),
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'family_history_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Brazilian family-history framing.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-wisconsin-prognostic',
      datasetFieldName: 'family_history_proxy',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Clinical prognostic proxy for hereditary context.',
    }),
  ],
  brcaTest: [
    createMapping({
      datasetReferenceSlug: 'gdc-data-portal',
      datasetFieldName: 'brca_genetics_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Genomic reference for BRCA-related context.',
    }),
    createMapping({
      datasetReferenceSlug: 'tcga-brca-project',
      datasetFieldName: 'brca_genetics_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Primary breast cancer genomics project.',
    }),
    createMapping({
      datasetReferenceSlug: 'cbioportal-metabric',
      datasetFieldName: 'molecular_subtype_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Genomic cohort reference for hereditary/biomarker context.',
    }),
    createMapping({
      datasetReferenceSlug: 'cbioportal-tcga-breast-invasive-carcinoma',
      datasetFieldName: 'molecular_subtype_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'PanCancer Atlas breast cancer cohort.',
    }),
    createMapping({
      datasetReferenceSlug: 'geo-gse96058',
      datasetFieldName: 'expression_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Transcriptomic support for biomarker-oriented expansion.',
    }),
  ],
  familyOvaryCancer: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'family_history_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Brazilian family history and associated cancer context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'family_history_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population family history context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'preventive_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global prevention guidance and family risk framing.',
    }),
    createMapping({
      datasetReferenceSlug: 'iarc-globocan-breast-fact-sheet',
      datasetFieldName: 'population_risk_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global epidemiology context for associated cancer history.',
    }),
  ],
  symptoms: [
    createMapping({
      datasetReferenceSlug: 'uci-mammographic-mass',
      datasetFieldName: 'symptom_and_mass_context',
      mappingType: 'primary',
      evidenceStrength: 'medium',
      notes: 'Mass-related clinical reference for symptom-oriented fields.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-tissue',
      datasetFieldName: 'tissue_classification_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Supports tissue and lesion-oriented symptom discussion.',
    }),
    createMapping({
      datasetReferenceSlug: 'cbis-ddsm',
      datasetFieldName: 'imaging_symptom_context',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Imaging benchmark for symptomatic lesion references.',
    }),
    createMapping({
      datasetReferenceSlug: 'breakhis',
      datasetFieldName: 'histopathology_symptom_context',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Histopathology benchmark for lesion-related symptoms.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-wisconsin-diagnostic',
      datasetFieldName: 'diagnostic_symptom_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Classic diagnostic benchmark reference.',
    }),
  ],
  mammogram: [
    createMapping({
      datasetReferenceSlug: 'uci-mammographic-mass',
      datasetFieldName: 'mammography_reference',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Direct mammographic mass reference.',
    }),
    createMapping({
      datasetReferenceSlug: 'cbis-ddsm',
      datasetFieldName: 'mammography_image_context',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Mammography imaging benchmark.',
    }),
    createMapping({
      datasetReferenceSlug: 'tcga-brca-imaging-collection',
      datasetFieldName: 'imaging_reference',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Future image-based comparison reference.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-tissue',
      datasetFieldName: 'tissue_mammogram_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Clinical tissue context tied to imaging.',
    }),
  ],
  breastPain: [
    createMapping({
      datasetReferenceSlug: 'uci-mammographic-mass',
      datasetFieldName: 'pain_and_mass_context',
      mappingType: 'primary',
      evidenceStrength: 'medium',
      notes: 'Symptom-oriented clinical proxy.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-tissue',
      datasetFieldName: 'pain_and_tissue_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Tissue-related symptom context.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-wisconsin-diagnostic',
      datasetFieldName: 'pain_and_diagnostic_context',
      mappingType: 'benchmark',
      evidenceStrength: 'medium',
      notes: 'Diagnostic benchmark for breast discomfort context.',
    }),
  ],
  hormonalContraceptive: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'hormonal_risk_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health source for hormonal exposure context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'hormonal_risk_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population-level hormonal factor context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'contraceptive_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global prevention and risk guidance.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-coimbra',
      datasetFieldName: 'reproductive_risk_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Clinical-metabolic context for reproductive risk.',
    }),
  ],
  hormoneReplacement: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'hormone_therapy_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health context for hormone replacement exposure.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'hormone_therapy_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population-level hormone therapy context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'postmenopausal_hormone_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global guidance around menopause and hormone therapy.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-coimbra',
      datasetFieldName: 'reproductive_risk_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Clinical-metabolic context.',
    }),
  ],
  menarche: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'reproductive_history_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health reproductive history context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'reproductive_history_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population-level menarche context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'reproductive_history_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global reproductive risk guidance.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-coimbra',
      datasetFieldName: 'metabolic_reproductive_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Clinical-metabolic context.',
    }),
  ],
  menopause: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'menopause_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health menopause context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'menopause_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population-level menopause context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'menopause_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global menopause and prevention guidance.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-recurrence-non-recurrence',
      datasetFieldName: 'outcome_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Prognostic benchmark for menopause-related follow-up context.',
    }),
  ],
  breastfed: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'breastfeeding_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health breastfeeding context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'breastfeeding_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population-level breastfeeding context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'breastfeeding_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global education guidance.',
    }),
    createMapping({
      datasetReferenceSlug: 'iarc-globocan-breast-fact-sheet',
      datasetFieldName: 'breastfeeding_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global epidemiology context.',
    }),
  ],
  physicalActivity: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'lifestyle_activity_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Lifestyle prevention context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'lifestyle_activity_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population lifestyle context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'physical_activity_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global prevention guidance.',
    }),
    createMapping({
      datasetReferenceSlug: 'iarc-globocan-breast-fact-sheet',
      datasetFieldName: 'lifestyle_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global risk context.',
    }),
  ],
  alcohol: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'alcohol_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health alcohol risk context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'alcohol_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population alcohol-risk context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'alcohol_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global prevention and behavior context.',
    }),
  ],
  smoking: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'smoking_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health smoking risk context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'smoking_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population smoking-risk context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'smoking_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global prevention and behavior guidance.',
    }),
  ],
  diet: [
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'nutrition_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Public health diet and prevention context.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'nutrition_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Population nutrition context.',
    }),
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-coimbra',
      datasetFieldName: 'diet_and_metabolic_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Clinical-metabolic proxy for diet patterns.',
    }),
  ],
  bmi: [
    createMapping({
      datasetReferenceSlug: 'uci-breast-cancer-coimbra',
      datasetFieldName: 'bmi_context',
      mappingType: 'primary',
      evidenceStrength: 'high',
      notes: 'Metabolic dataset with BMI relevance.',
    }),
    createMapping({
      datasetReferenceSlug: 'seer-female-breast-cancer-stat-facts',
      datasetFieldName: 'bmi_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Population BMI context.',
    }),
    createMapping({
      datasetReferenceSlug: 'inca-dados-e-numeros',
      datasetFieldName: 'bmi_context',
      mappingType: 'supporting',
      evidenceStrength: 'medium',
      notes: 'Public health BMI and prevention context.',
    }),
    createMapping({
      datasetReferenceSlug: 'who-breast-cancer-fact-sheet',
      datasetFieldName: 'bmi_context',
      mappingType: 'supporting',
      evidenceStrength: 'contextual',
      notes: 'Global guidance on weight and cancer prevention.',
    }),
  ],
}

export const DATASET_FEATURE_MAPPINGS = Object.entries(FIELD_DATASET_MAPPINGS).flatMap(
  ([projectFieldKey, mappings]) =>
    mappings.map((mapping) => ({
      projectFieldKey,
      ...mapping,
    })),
)

export const RISK_MODEL_VERSIONS = [
  {
    version: RISK_MODEL_VERSION,
    name: 'RiskCare Heuristic v1',
    description: 'Heuristic model using epidemiological, contextual, and clinical references.',
    thresholdsJson: {
      ...CLASSIFICATION_THRESHOLDS,
      highMax: 100,
    },
    weightsJson: {
      groupWeights: GROUP_WEIGHTS,
      groupFactorWeights: GROUP_FACTOR_WEIGHTS,
    },
    active: true,
  },
]

export function getCatalogCoverageReport() {
  return Object.entries(FIELD_DATASET_MAPPINGS).map(([projectFieldKey, mappings]) => ({
    projectFieldKey,
    mappedDatasetCount: mappings.length,
    datasetSlugs: mappings.map((mapping) => mapping.datasetReferenceSlug),
  }))
}

export function assertCatalogCoverage(fieldMappingKeys) {
  const missingKeys = fieldMappingKeys.filter((key) => !FIELD_DATASET_MAPPINGS[key])

  if (missingKeys.length > 0) {
    throw new Error(`Missing dataset mappings for fields: ${missingKeys.join(', ')}`)
  }

  return true
}
